#!/usr/bin/env Rscript
# vim: ft=r

source('functions.R')

args <- commandArgs(TRUE)
cmd <- args[1]

# settings
BUDGET <- as.numeric(getVar('BUDGET', 200))
ROSTER <- as.numeric(getVar('ROSTER', 15))
POSITIONS <- getVar('POSITIONS', c('QB', 'WR', 'RB', 'TE', 'K', 'DEF'))
TEAMS <- getVar('TEAMS', NULL)

draft <- read.draft('draft', POSITIONS, TEAMS)

# filter
if (length(args) >= 2) {
    draft <- filter(args[2])
}

if (is.na(cmd)) {
    # print usage
    cat('Commands
    money [team]        Display the finances.
    roster team         Display a team\'s roster.
    breakdown [team]    Display the roster breakdowns.
')
    q()
}

if (cmd == 'money') {
    money()
}

if (cmd == 'roster') {
    if (length(args) < 2) stop('this command requires a team argument')
    roster(args[2])
}

if (cmd == 'breakdown') {
    breakdown()
}
